// Builds seed.sql FROM the live trading-sim files.
// Usage: node scripts/build-seed.js
// Reads: ~/workspace/trading-sim/portfolios/current_state.json
//        ~/workspace/trading-sim/transactions/all_transactions.csv
//        ~/workspace/trading-sim/brain/STRATEGY_MEMORY.md  (as intelligence v1)
// Writes: seed.sql (idempotent — DELETEs then INSERTs).
// If a source file is mid-write (parse error), retries once after 2s.

import { readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";

const SIM = join(homedir(), "workspace", "trading-sim");
const OUT = join(homedir(), "workspace", "trader-portal", "seed.sql");

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const q = (s) => `'${String(s ?? "").replaceAll("'", "''")}'`;
const qn = (s) => (s == null || s === "" ? "NULL" : q(s));

function readJsonRetry(path) {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      return JSON.parse(readFileSync(path, "utf8"));
    } catch (e) {
      if (attempt === 0) console.error(`parse failed for ${path}, retrying once...`);
      else throw e;
    }
    // brief pause before retry (sync-ish)
    const end = Date.now() + 2000;
    while (Date.now() < end) { /* busy wait, fine for a seed script */ }
  }
}

// Minimal RFC-4180 CSV parser (handles quoted fields with commas/quotes).
function parseCsv(text) {
  const rows = [];
  let row = [], field = "", inQ = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQ) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else inQ = false;
      } else field += c;
    } else if (c === '"') inQ = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (c === "\r") { /* skip */ }
    else field += c;
  }
  if (field !== "" || row.length) { row.push(field); rows.push(row); }
  return rows.filter((r) => r.length > 1 || r[0].trim() !== "");
}

async function main() {
  const state = readJsonRetry(join(SIM, "portfolios", "current_state.json"));
  const csvText = readFileSync(join(SIM, "transactions", "all_transactions.csv"), "utf8");
  const memoryMd = readFileSync(join(SIM, "brain", "STRATEGY_MEMORY.md"), "utf8");
  const exportedAt = new Date().toISOString();

  const L = [];
  L.push("-- seed.sql — GENERATED by scripts/build-seed.js from live trading-sim files.");
  L.push(`-- Generated at ${exportedAt}. Re-run \`npm run seed\` to refresh.`);
  L.push("-- PAPER TRADING ONLY.");
  L.push("");

  // --- agents (keys issued later via admin rotate-key) ---
  L.push("DELETE FROM agent_contributions;");
  L.push("DELETE FROM community_agent_profiles;");
  L.push("DELETE FROM agents;");
  const agents = [
    ["muse", "Muse", "llm", "pending"],
    ["instinct", "Instinct", "llm", "pending"],
    ["sivaganesh", "Sivaganesh", "human", "online"],
  ];
  for (const [id, name, type, status] of agents) {
    L.push(
      `INSERT INTO agents (id, name, type, api_key_hash, status, created_at) VALUES (${q(id)}, ${q(name)}, ${q(type)}, NULL, ${q(status)}, ${q(exportedAt)});`
    );
  }
  L.push("");

  // --- portfolio snapshots ---
  L.push("DELETE FROM portfolio_snapshots;");
  for (const key of ["india_inr", "us_usd", "crypto"]) {
    const pf = state.portfolios[key];
    if (!pf) continue;
    L.push(
      `INSERT INTO portfolio_snapshots (portfolio, snapshot_json, created_at) VALUES (${q(key)}, ${q(JSON.stringify(pf))}, ${q(exportedAt)});`
    );
  }
  L.push("");

  // --- transactions (mirror of all_transactions.csv) ---
  L.push("DELETE FROM transactions;");
  const rows = parseCsv(csvText);
  const header = rows[0].map((h) => h.trim());
  const idx = (name) => header.indexOf(name);
  let n = 0;
  for (const r of rows.slice(1)) {
    n++;
    const id = `txn_${String(n).padStart(3, "0")}`;
    L.push(
      `INSERT INTO transactions (id, ts, portfolio, action, symbol, qty, price, currency, value, price_source, justification, decided_by)` +
      ` VALUES (${q(id)}, ${q(r[idx("timestamp")])}, ${q(r[idx("portfolio")])}, ${q(r[idx("type")])}, ${q(r[idx("symbol")])},` +
      ` ${Number(r[idx("quantity")])}, ${Number(r[idx("price")])}, ${q(r[idx("currency")])}, ${Number(r[idx("value")])},` +
      ` ${q(r[idx("source")])}, ${q(r[idx("short_justification")])}, 'legacy');`
    );
  }
  L.push("");

  // --- intelligence v1 (strategy memory export), stored in 20KB chunks ---
  L.push("DELETE FROM intelligence_chunks;");
  L.push("DELETE FROM intelligence_versions;");
  const intelJson = JSON.stringify({
    version: 1,
    source: "trading-sim/brain/STRATEGY_MEMORY.md",
    exported_at: exportedAt,
    note: "Seeded from the live trading brain. Download the markdown for the full journal.",
  });
  L.push(
    `INSERT INTO intelligence_versions (version, meta_json, created_at) VALUES (1, ${q(intelJson)}, ${q(exportedAt)});`
  );
  const CHUNK = 20000;
  let seq = 0;
  for (let i = 0; i < memoryMd.length; i += CHUNK) {
    L.push(`INSERT INTO intelligence_chunks (version, seq, chunk) VALUES (1, ${seq}, ${q(memoryMd.slice(i, i + CHUNK))});`);
    seq++;
  }
  L.push("");

  // --- welcome chat message ---
  L.push("DELETE FROM chat_messages;");
  L.push(
    `INSERT INTO chat_messages (agent_id, body, created_at) VALUES (NULL, ${q(
      "🏁 Portal seeded from the live trading simulator. 11 legacy transactions imported. " +
      "Agents: register via the admin API to get a bearer key, then heartbeat + poll /api/chat and /api/proposals every ≤60s. " +
      "Paper trading only — no real money, ever."
    )}, ${q(exportedAt)});`
  );

  writeFileSync(OUT, L.join("\n") + "\n", "utf8");
  console.log(`wrote ${OUT}: ${n} transactions, 3 portfolio snapshots, intelligence v1 (${memoryMd.length} chars)`);
}

main().catch((e) => { console.error(e); process.exit(1); });
